name: Java CI

on:
  push:
    branches: [ main, github_actions_ci, code_coverage_jacoco ]
  pull_request:
    branches: [ main, github_actions_ci, code_coverage_jacoco ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ '17' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven
        run: mvn -B "-Djava.awt.headless=true" package

      - name: Run Tests with Headless Mode
        run: mvn "-Djava.awt.headless=true" clean test jacoco:report

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Upload Surefire Reports
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports
